- name: Installation Nginx webserver
  ansible.builtin.apt:
    name: nginx
    state: present
  become: yes

- name: Nginx configuration
  ansible.builtin.copy:
    src: files/nginx/nginx.conf
    dest: /etc/nginx/conf.d/nginx.conf 
  become: yes
  notify: 
    - restart_nginx
    
- name: Creation de /srv/app 
  ansible.builtin.file:
    path: /srv/app
    state: directory
    owner: www-data
    mode: '0755'
  become: yes


- name: deploiement des pages PHP
  ansible.builtin.copy:
    src: files/php/index.php
    dest: /srv/app/index.php
    owner: www-data
    mode: '0644'
  become: yes



