- name: Installation MySql
  ansible.builtin.apt:
    name: default-mysql-server
    state: present
  become: yes
  tags:
    - mysql

- name: Installation Python MySql
  ansible.builtin.apt:
    name: python3-mysqldb
    state: present
  become: yes

- name: Creation de base de données staging
  mysql_db:
    name: "{{ db_name2 }}"
    state: present
  become: yes

- name: Creation staging MySQL user
  mysql_user:
    name: "{{ user2 }}"
    password: "{{ mysql_st }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
  become: yes
  vars:
    column_case_sensitive: false

- name: Creation de base de données production
  mysql_db:
    name: "{{ db_name1 }}"
    state: present
  become: yes
  
- name: Creation production MySQL user
  mysql_user:
    name: "{{ user1 }}"
    password: "{{ mysql_pr }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
  become: yes
  notify:
    - restart_mysql
  vars:
    column_case_sensitive: false
