all:

  hosts:

    vm-production-01:
      ansible_host: 152.228.212.65
      ansible_user: debian
      
    vm-staging-01:
      ansible_host: 152.228.211.237
      ansible_user: debian

  children:

    webservers:

      hosts:

        vm-production-01: ~
        vm-staging-01: ~

    dbservers:

      hosts:

        vm-production-01: ~
        vm-staging-01: ~

    staging:

      hosts:

        vm-staging-01: ~

    production:

      hosts:

        vm-production-01: ~        